name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      env:
        DATOMIC_USER : ${{secrets.DATOMIC_USER}}
        DATOMIC_USER_PASS : ${{secrets.DATOMIC_USER_PASS}}
      run: lein deps
    - name: Run tests
      run: lein test